### ISSUE TITLE
Custom metrics input values should be split with space not tab

### ISSUE THREAD

**Issue by doublemarket** [mackerelio/mackerel-agent#118]
According to the [Mackerel document](http://help.mackerel.io/entry/advanced/custom-metrics), custom metrics plugins should output tab-separated values as follows;

```
{metric name}\t{metric value}\t{epoch seconds}
```

but Sensu plugins using Sensu::Plugin::Metric::CLI::Graphite output space-separated values;

https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-plugin/metric/cli.rb#L26

so if you say the format is "compatible with sensu", the parser should split values with spaces not tabs or both of them.

https://github.com/mackerelio/mackerel-agent/blob/master/metrics/plugin.go#L231

**Comment by Songmu** [comment]
Thank you! I'll fix it soon.

**Comment by Songmu** [comment]
fixed. I'll inform you when the next version of the mackerel-agent is released. @doublemarket

**Comment by doublemarket** [comment]
Thanks for quick fixing.
I look forward to the next release!

**Comment by Songmu** [comment]
Released as v0.18.1. Please try it. Thank you. @doublemarket

**Comment by mhayato** [comment]
Thank you very much! I'll try it soon.
