### ISSUE TITLE
cpu usage is wrong

### ISSUE THREAD

**Issue by lostz** [mackerelio/mackerel-agent#138]
ret[name+".percentage"] = (currValues[i] - prevValues[i]) * 100.0 * float64(cpuCount) / (currTotal - prevTotal)

no need cpucount 
right is 

ret[name+".percentage"] = (currValues[i] - prevValues[i]) * 100.0  / (currTotal - prevTotal)

**Comment by Songmu** [comment]
Thank you for feedback.

It is style matter.
We mackerel treat maximum CPU percentage of 8 core machine as 800%.
