### ISSUE TITLE
Can I ignore some of drives on filesystem check?

### ISSUE THREAD

**Issue by udzura** [mackerelio/mackerel-agent#160]
Hi, thanks great service && ecosystems.

We have used mackerel agents for many hosts, and found that some drives always raises alerts of disk full.

```console
$ LANG=C df -P
Filesystem              1024-blocks    Used Available Capacity Mounted on
/dev/mapper/centos-root    82929664 3794152  79135512       5% /
devtmpfs                    8125124       0   8125124       0% /dev
tmpfs                       8134412       0   8134412       0% /dev/shm
tmpfs                       8134412  164124   7970288       3% /run
tmpfs                       8134412       0   8134412       0% /sys/fs/cgroup
/dev/sr0                        422     422         0     100% /mnt/config-drive
/dev/vda1                    508588  165184    343404      33% /boot
```

`/dev/sr0` is a CD-ROM drive, so it seems to be unreasonable to warn us of disk usage.

(Especially, OpenStack distributes its metadata to instances via CD-ROM drive according to its construction settings, then in some cases, there always exists `/dev/sr0` and uses 100% drive.)

So we may feel happy if some of drives are able to be ignored by its filesystem type(e.g. ign `iso9660`), or by its name.

Thanks!

（もし詳細がよくわからなければ、twitter等で日本語で説明させていただきます...）

**Comment by Songmu** [comment]
なるほど…

**Comment by stanaka** [comment]
https://github.com/mackerelio/mackerel-agent/pull/186 will fix this
