### ISSUE TITLE
signing key is weak (1024bit dsa)

### ISSUE THREAD

**Issue by hidekiy** [mackerelio/mackerel-agent#204]
I think at least 2048R key is required in 2016.

```
$ gpg GPG-KEY-mackerel
pub  1024D/C2B48821 2014-05-08 Hatena Inc. <admin@mackerel.io>
```

**Comment by Songmu** [comment]
Thank you for feedback. We'll try to change the key.

**Comment by hidekiy** [comment]
Thanks!!!

**Comment by Songmu** [comment]
We released v2 repositories signed with SHA-256, resolving this issue.

https://mackerel.io/blog/entry/announcement/20170616

Thanks for your reporting.

**Comment by hidekiy** [comment]
Congrats!!
