### ISSUE TITLE
fatal error: s.allocCount != s.nelems && freeIndex == s.nelems

### ISSUE THREAD

**Issue by toruuetani** [mackerelio/mackerel-agent#390]
I received this error twice.
Is there a way to avoid this?

I instlled mackerel-agent from binary.
Ver: 042.3
CPU: 1 x ARM926EJ-S rev 4 (v5l)
OS: GNU/Linux 3.10.37-3.10.37-klk4

**Comment by astj** [comment]
Is there any other stacktraces and/or logs when the error happened?

**Comment by toruuetani** [comment]
Sorry, I was supposed to attach a file, but I could not do it.
I tried again.

[mackerel.2017-05-22.txt](https://github.com/mackerelio/mackerel-agent/files/1025817/mackerel.2017-05-22.txt)
[mackerel-20170524.txt](https://github.com/mackerelio/mackerel-agent/files/1025818/mackerel-20170524.txt)

**Comment by astj** [comment]
Thank you. I'll take a look.

**Comment by mattn** [comment]
most similarly this, but MIPS: https://github.com/golang/go/issues/16848

**Comment by mattn** [comment]
@toruuetani Does your environment meet the requirements indicated by below?

https://github.com/golang/go/wiki/MinimumRequirements#arm

**Comment by astj** [comment]
Maybe `ARM926EJ-S rev 4 (v5l)` is ARMv5 (ref: https://www.arm.com/products/processors/classic/arm9/arm926.php), and default go cross compiling will compile with `GOARM=6`!

**Comment by astj** [comment]
Compiling mackerel-agent manually for ARMv5 (`GOOS=linux GOARCH=arm GOARM=5 make build` will build `build/mackerel-agent`) may solve the issue.

But please note we don't support running mackerel-agent on ARM architectures officially.

**Comment by toruuetani** [comment]
@mattn Tkanks. I will check the requirements.

@astj Thanks. I will build from source. 
And I understand not supported.

**Comment by toruuetani** [comment]
I built mackerel-agent v0.43.1 with current shirou/gopsutil.
I will see a state for a while.

**Comment by astj** [comment]
@toruuetani 
OK. I'll close this issue once. If the error happens again, please reopen this issue.

**Comment by toruuetani** [comment]
I am very sorry, but the error has recurred.
But I can't re-open this issue. So please re-open this issue.

I received below log with mackerel-agent v0.43.1 with current shirou/goputils.

[mackerel-agent-2017-05-28.txt](https://github.com/mackerelio/mackerel-agent/files/1034670/mackerel-agent-2017-05-28.txt)

**Comment by astj** [comment]
Sorry for late response.
It happened in internal of go (it just `make` ing a `map`...) therefore currently we have nothing to do about it. Building with latest go may help, but may not help...

Thank you again for reporting.

**Comment by toruuetani** [comment]
Thank you for response.
And I understood this difficulty.  So just forget about this.
