### ISSUE TITLE
Unable to restart mackerel-agent with slow cloud meta-data service

### ISSUE THREAD

**Issue by hanazuki** [mackerelio/mackerel-agent#412]
Since recent update Custom Identifier (eg. AWS instance id) check is introduced( https://github.com/mackerelio/mackerel-agent/pull/405 ). This check ensures that the Custom Identifier of the current instance matches the one previously stored on the mackerel.io server for the HostID. In our setup, this check prevents mackerel-agent to start up.

The Custom Identifier of the current instance is fetched from the cloud meta-data service (i.e. http://169.25.169.254 in case of AWS). The meta-data service is expected to return response within 100ms:
https://github.com/mackerelio/mackerel-agent/blob/6798d53774ecdf5298c503d13bd6344a244afe5b/spec/cloud.go#L47

When the meta-data service is unable to respond within 100ms, an empty string is used as the Custom Identifier of the current instance, which does not match the one successfully stored on the server in the previous agent run.
https://github.com/mackerelio/mackerel-agent/blob/369b9325e878fc362bebbde7980bbe32cb4b8e74/command/command.go#L108-L113
(`customIdentifier = ""` and `result.CustomIdentifier = (previously stored instance-id)`)

We use OpenStack, which provides AWS-compatible meta-data service at 169.254.169.254, but in our setup it sometimes take a bit longer than 100ms to respond. Due to the reason described above, we are having trouble that mackerel-agent often fails to restart.

I have some idea to deal with this problem,
- Add an option to extend the HTTP timeout for the meta-data service,
- Add an option to disable cloud meta-data retrieval, or
- Skip the check when the Custom Identifier cannot be fetched for some reason.

Which one is preferred? I can provide a patch for the solutions if necessary.

**Comment by itchyny** [comment]
Thank you. I think we can simply extend the default timeout (adding an option for this would not be a good idea). IMO 5 seconds for timeout is acceptable. What do you think? @mechairoi @Songmu

**Comment by hanazuki** [comment]
I have missed https://github.com/mackerelio/mackerel-agent/pull/401 . My description above seems  wrong.

Before #401, VM instances on our OpenStack pass `isEC2` check since the AWS-compatible meta-data service returns ami-id. After the change, they don't because the kernel do not have /sys/hypervisor/uuid and thus Custom Identifier seems not fetched from the meta-data service.

**Comment by Songmu** [comment]
The timeout duration is 3 seconds now. There is also a way to explicitly specify `cloud_platform =" ec2 "` in the configuration file.

Close this issue as it has already been resolved.
