### ISSUE TITLE
metrics/linux/cpuusage.go is inacculate if a host runs KVM VMs

### ISSUE THREAD

**Issue by hiboma** [mackerelio/mackerel-agent#419]
Hi.

I've found that `metrics/linux/cpuusage.go` calucurates **user** inaccurately on Linux hosts running KVM vms.

## What's inaccurate?

As you can see `man 5 proc`, 1st column of `/proc/stat` means  ***user   (1) Time spent in user mode***, and 9th column means ***guest (9) Time spent running a virtual CPU for guest operating systems under the control of the Linux kernel***. 

Acutually, **user** includes **guest**, so cputime is duplicated, if host running KVM vms. ( ... it is undocumented 😭 )

## Evidence

In Linux kernel sources, **user** is accounted as `cputime[CPUTIME_USER]` and **guest** is as `cputime[CPUTIME_GUEST]`,  by `account_guest_time`

Here is a source of 4.14-rc3

```c
/*
 * Account guest cpu time to a process.
 * @p: the process that the cpu time gets accounted to
 * @cputime: the cpu time spent in virtual machine since the last update
 */
void account_guest_time(struct task_struct *p, u64 cputime)
{
	u64 *cpustat = kcpustat_this_cpu->cpustat;

	/* Add guest time to process. */
	p->utime += cputime;
	account_group_user_time(p, cputime);
	p->gtime += cputime;

	/* Add guest time to cpustat. */
	if (task_nice(p) > 0) {
		cpustat[CPUTIME_NICE] += cputime;
		cpustat[CPUTIME_GUEST_NICE] += cputime;
	} else {
		cpustat[CPUTIME_USER] += cputime; ⭐
		cpustat[CPUTIME_GUEST] += cputime; ⭐
	}
}
```

In case `task_struct` is virtual machine (e.g. KVM), `account_guest_time` accounts `cputime` to both `cpustat[CPUTIME_USER]` and `cpustat[CPUTIME_GUEST]`.

`account_guest_time` has been introduced in v2.6.24-rc1. ( https://github.com/torvalds/linux/commit/94886b84b1bcdc95f34f70e7fce407efefe472e1 )

```c
/*
 * Account guest cpu time to a process.
 * @p: the process that the cpu time gets accounted to
 * @cputime: the cpu time spent in virtual machine since the last update
 */
void account_guest_time(struct task_struct *p, cputime_t cputime)
{
	cputime64_t tmp;
	struct cpu_usage_stat *cpustat = &kstat_this_cpu.cpustat;

	tmp = cputime_to_cputime64(cputime);

	p->utime = cputime_add(p->utime, cputime);
	p->gtime = cputime_add(p->gtime, cputime);

	cpustat->user = cputime64_add(cpustat->user, tmp);
	cpustat->guest = cputime64_add(cpustat->guest, tmp);
}
```

## How to correct ?

Subtracting **guest** time from **user** time. 

```
user = user - guest
```

#### Example 

Here is `mpstat` implementation.

https://github.com/sysstat/sysstat/blob/master/mpstat.c#L529-L568 (d7321c1)

```c
/*
 ***************************************************************************
 * Display CPU statistics in JSON format.
 *
 * IN:
 * @tab		Number of tabs to print.
 * @g_itv	Interval value in jiffies multiplied by the number of CPU.
 * @prev	Position in array where statistics used	as reference are.
 *		Stats used as reference may be the previous ones read, or
 *		the very first ones when calculating the average.
 * @curr	Position in array where current statistics will be saved.
 ***************************************************************************
 */
void write_json_cpu_stats(int tab, unsigned long long g_itv, int prev, int curr)
{
	struct stats_cpu *scc, *scp;
	unsigned long long pc_itv;
	int cpu, next = FALSE;

	xprintf(tab++, "\"cpu-load\": [");

	/* Check if we want global stats among all proc */
	if (*cpu_bitmap & 1) {

		next = TRUE;
		xprintf0(tab, "{\"cpu\": \"all\", \"usr\": %.2f, \"nice\": %.2f, \"sys\": %.2f, "
			      "\"iowait\": %.2f, \"irq\": %.2f, \"soft\": %.2f, \"steal\": %.2f, "
			      "\"guest\": %.2f, \"gnice\": %.2f, \"idle\": %.2f}",
			 (st_cpu[curr]->cpu_user - st_cpu[curr]->cpu_guest) < ⭐
			 (st_cpu[prev]->cpu_user - st_cpu[prev]->cpu_guest) ? ⭐
			 0.0 :
			 ll_sp_value(st_cpu[prev]->cpu_user - st_cpu[prev]->cpu_guest, ⭐
				     st_cpu[curr]->cpu_user - st_cpu[curr]->cpu_guest, ⭐
				     g_itv),


```

⭐ are the points I mentioned above.

Also https://github.com/torvalds/linux/commit/94886b84b1bcdc95f34f70e7fce407efefe472e1 said 

> A modified "top(1)" is able to display good cpu user time and cpu guest
time by subtracting cpu guest time from cpu user time. Update "gtime" in
task_struct accordingly.

----

## 日本語

仮想マシン KVM で動かしている Linux ホストで `metrics/linux/cpuusage.go` の user と guest 時間が正確に表示できないので issue をたてました

 * Linux をホストとして KVM でゲストを実行していると、 `/proc/stat` が返す user 時間に guest 時間が余分に加算されます (カーネルのソースを参照してください)
 * 解決するには user 時間から guest 時間を減算するよいです (mpstat のソースや　`account_guest_time` が追加された際のコミットログを参考にしてください)

**Comment by itchyny** [comment]
Thank you for your issue report, I opened a pull request in #423. Please take a quick look.

**Comment by hiboma** [comment]
Sorry for late reply ( I was on vacation ✈ ). Thank you for fixing 👍
