### ISSUE TITLE
spec.block_device error to use mackerel agent on Heroku

### ISSUE THREAD

**Issue by ukisoft** [mackerelio/mackerel-agent#421]
Hi,

I installed mackerel-agent with [this article](https://mackerel.io/ja/docs/entry/advanced/monitoring-heroku) on Heroku,
then there are some errors like below every hour:

```
block_device.go:29: ERROR <spec.block_device> Failed (skip this spec): open /sys/block: no such file or directory
```

I use only 1 dyno, and Django is working on Heroku.
How do I do to stop this error ?

Thanks.

**Comment by itchyny** [comment]
Thank you for your report. I confirmed that the `/sys/block` directory is unavailable on Dyno, while we assume that the directory is available on Linux (EC2 as well). The message is not a critical error for mackerel-agent on Dyno so you can ignore the message. We'll discuss how to deal with the issue (maybe make the log level to warning?).

**Comment by ukisoft** [comment]
I see.
Thank you so much.
