### ISSUE TITLE
I wrote rc script for FreeBSD but I don't know where I would put this when I send PR

### ISSUE THREAD

**Issue by owatan** [mackerelio/mackerel-agent#558]
https://github.com/owatan/mackerel-agent/commit/7a85fb4e987827abcdc219273142e1a6ffa56e81

Hi.

I read [Installing mackerel-agent in binary - Mackerel Docs](https://mackerel.io/docs/entry/howto/install-agent/binary), so
I wrote rc script for FreeBSD , but I don't know where I would put this file when I send pull-request.

I checked operation verification on `FreeBSD 11.2-RELEASE`, and `FreeBSD 12.0-RELEASE`.

## 日本語
[バイナリファイルで直接mackerel-agentをインストールする - Mackerel ヘルプ](https://mackerel.io/ja/docs/entry/howto/install-agent/binary) を読むと

> ご利用の環境にあわせてサービス化してください。

とあったので FreeBSD で mackerel-agent をサービス化するスクリプトを書きましたが、
これが (一般に) 提供されていればより使いやすくなるのではないか、と思い PR を送ろうとした次第です。

[mackerelio/mackerel-agent](https://github.com/mackerelio/mackerel-agent/) のレポジトリを見ても、このファイルを追加する PR を出す際に、どこに置けば良いのか分からなかったため、ひとまずこの Issue を立てました。

`FreeBSD 11.2-RELEASE` および `FreeBSD 12.0-RELEASE` で実際に動作することを確認しています。

**Comment by astj** [comment]
@owatan 
Thank you for nice suggestion!
How about `./packaging/freebsd/` ?
I don't think it's the BEST directory but at least acceptable, so it's reasonable to start with the directory.

**Comment by owatan** [comment]
@astj Thanks to check and comment!
I added with README to `./packaging/freebsd/`.
I will be happy when you would check this pull-request #559 .

**Comment by astj** [comment]
I'd like to close this issue, since I merged #559. Thank you!
