### ISSUE TITLE
ビルドできません：_tools/go-linter: golint: not found

### ISSUE THREAD

**Issue by Tomon613** [mackerelio/mackerel-agent#619]
makeにてmackerel-agentのソースコンパイルを試みたところ、
```
_tools/go-linter: golint: not found
*** Error code 127
```
にてコケてビルドできません。golintはインストール済みの状態でこのエラーが出ます。

環境はmacOS、gopathは$HOME/goに、バージョンは1.13.4（goenv経由）を使用しています。

make build、make runじゃないとできないのですかね？

**Comment by syou6162** [comment]
質問ありがとうございます。このリポジトリは海外の方からもissueやpull-requestをいただく場合もあり、今後のコミュニケーションは英語でおこなわせていただければと思います。

日本語でのコミュニケーションが必要な場合は、support@mackerel.io にお問い合わせいただくか、
Mackerel User Group の slack をご利用ください。
https://mackerel-ug-slackin.herokuapp.com/

@Tomon613 Hi, thank you for reporting.

Tha path for `golint` in Makefile is define below:

- https://github.com/mackerelio/mackerel-agent/blob/master/Makefile#L9-L11

The path for `golint` in your environment (via goenv) is different from one which is defined in Makefile. Could you check that?
