### ISSUE TITLE
`setup-all-apt-v2.sh` uses the deprecated `apt-key` command

### ISSUE THREAD

**Issue by cktkw** [mackerelio/mackerel-agent#761]
I'm sorry if this is not the right place to report issues related to `setup-all-apt-v2.sh`, which is not part of this repository, but I was not aware of anywhere else better.

The installer script `setup-all-apt-v2.sh` currently uses the `apt-key` command to add the repository's key to APT's trusted keyring, but this method has been deprecated due to security reasons.
According to the [Debian's document](https://wiki.debian.org/DebianRepository/UseThirdParty) the recommend method is to create a new GPG key ring in some location (such as `/usr/share/keyrings/mackerel.gpg`) and then pin the repository signature to it in the APT source file

    deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/mackerel.gpg] http://apt.mackerel.io/v2/ mackerel contrib

PS: I am not a security expert nor a Debian committer so I can't take responsibility for the correctness of the above method.

**Comment by pyto86pri** [comment]
Thank you for reporting.
We understand this issue. We'll work on it.

**Comment by pyto86pri** [comment]
We fixed `setup-all-apt-v2.sh` and not the script doesn't use `apt-key` command.

Close this issue as it has already been resolved.
