### ISSUE TITLE
Contents of suggestion when executing configtest may not be correct

### ISSUE THREAD

**Issue by ryuichi1208** [mackerelio/mackerel-agent#829]
If you create a config file like the one below and run configtest, a suggestion will be output to warnings. However, I could not understand the meaning of this content. Is this correct behavior?

```
apikey = "aaa"

[plugin.metrics.aaa]
command = ["exit 1"]
[plugin.metrics.aaa.bbb] ← Target of warning
command = ["exit 2"]
```

```
$ mackerel-agent version
mackerel-agent version 0.73.2 (rev 3fd96af) [darwin amd64 go1.19]

$ mackerel-agent configtest -conf a.conf
[WARNING] plugin.metrics.aaa.bbb is unexpected key.
[WARNING] plugin.metrics.aaa.bbb.command is unexpected key. did you mean plugin.metrics.aaa.bbb.command ?
```

**Comment by Arthur1** [comment]
@ryuichi1208 

As you pointed out, this suggestion in the error message is inappropriate. Thank you for letting us know! Your Pull Request will also be reviewed later.

**Comment by Arthur1** [comment]
@ryuichi1208 [mackerel-agent v0.73.3](https://github.com/mackerelio/mackerel-agent/releases/tag/v0.73.3)  including your pull request has been released. Thank you for your contribution!

**Comment by Arthur1** [comment]
@wafuwafu13 Can you work on the refactoring for configtest as a separate issue? We close this issue.
