### ISSUE TITLE
 osname is wrong on Windows 11

### ISSUE THREAD

**Issue by Arthur1** [mackerelio/mackerel-agent#850]
If you install mackerel-agent on a Windows 11 host, it is registered with Mackerel as a  Windows 10 host.

<img width="637" alt="スクリーンショット 2023-01-10 18 44 57" src="https://user-images.githubusercontent.com/32762324/211521120-0f242573-6724-4c70-9d84-550365afc9d7.png">

The result of obtaining os name by Get-Computerinfo command is shown below.

```
PS C:\Users\arthur> Get-ComputerInfo | Select OsName, OsDisplayVersion, OsBuildNumber                                   
OsName                   OSDisplayVersion OsBuildNumber
------                   ---------------- -------------
Microsoft Windows 11 Pro 22H2             22621
```

`osname` is taken from the registry `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\ProductName` value, but this implementation may not be sufficient. On a Windows 11 PC, this registry value is still `"Windows 10"`.

https://github.com/mackerelio/mackerel-agent/blob/7417ef2be05e88c815ddc8a4002ba32a6b74d16c/spec/windows/kernel.go#L25-L26

**Comment by Arthur1** [comment]
I tried the implementation using WMI. We can obtain OS name as Windows 11 with this method.

https://github.com/Arthur1/windows-version-go

**Comment by kmuto** [comment]
I confirmed my Windows 11 Professional PC was shown as "Windows 11 Pro" on Mackerel after updating mackerel-agent, without rebooting OS. Thanks!
